services:
  - type: web
    name: heroesdelplaneta
    env: python
    runtime: python-3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi"
    plan: free

    
